site_name: Playground
site_author: hardikdava
site_url: https://hardikdava.github.io/playground/
site_description: Repo for testing automation stuff.
repo_name: playground
repo_url: https://github.com/hardikdava/playground
edit_uri: tree/main/docs
copyright: All rights reserved.

nav:
  - Configuration: config.md
  - Development:
      - Development: development.md
  - Data:
    - Pipeline Steps: pipeline_steps.md
    - Input Quality Metrics: input_quality_metrics.md

plugins:
  - search
  - mermaid2

# Messages shown during document build
# Reference: https://www.mkdocs.org/user-guide/configuration/#validation
# Values: [warn, info, ignore]
validation:
  nav:
    absolute_links: ignore
  links:
    absolute_links: ignore
