name: Deploy MkDocs
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install mkdocs==1.6.1
          pip install mkdocstrings==0.26.2
          pip install mkdocs-mermaid2-plugin==1.1.1

      - name: Configure for staging
        if: github.ref == 'refs/heads/staging'
        run: |
          # Create or modify mkdocs staging config
          cp mkdocs.yml mkdocs.staging.yml
          sed -i 's/site_name:.*/site_name: "Gen2AI Staging"/' mkdocs.staging.yml
          sed -i 's#site_url:.*#site_url: https://username.github.io/repo-name/staging/#' mkdocs.staging.yml

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        run: |
          mkdocs gh-deploy --config-file mkdocs.staging.yml --remote-branch gh-pages --remote-name origin --force

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          mkdocs gh-deploy --remote-branch gh-pages --remote-name origin --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
